#ifndef TOKENTYPE_H
#define TOKENTYPE_H
enum type_of_token
{
	TOKEN_NULL, 
	TOKEN_AND, TOKEN_BEGIN, TOKEN_BOOL, TOKEN_CHAR, TOKEN_DO, TOKEN_ELSE, TOKEN_END, TOKEN_IF, TOKEN_FALSE, TOKEN_INT, 
	TOKEN_NOT, TOKEN_OR, TOKEN_PROGRAM, TOKEN_READ, TOKEN_THEN, TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE, TOKEN_WRITE, 
	TOKEN_FIN, TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_COLON, TOKEN_ASSIGN, TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_EQ, TOKEN_LSS, 
	TOKEN_GTR, TOKEN_PLUS, TOKEN_MINUS, TOKEN_TIMES, TOKEN_SLASH, TOKEN_LEQ, TOKEN_NEQ, TOKEN_GEQ, 
	TOKEN_NUM, TOKEN_ID, POLIZ_LABEL, POLIZ_ADDRESS, POLIZ_GO,POLIZ_FGO
}; 
#endif